"""initial models

Revision ID: 75d67f78a4d3
Revises: 
Create Date: 2024-02-04 14:01:36.353701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d67f78a4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('bill_type', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('election_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_registration_deadline', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_deployment_date', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_return_opening', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_return_deadline', sa.Date(), nullable=True),
    sa.Column('mail_in_ballot_postmark_deadline', sa.Date(), nullable=True),
    sa.Column('early_in_person_voting_opening', sa.Date(), nullable=True),
    sa.Column('early_in_person_voting_deadline', sa.Date(), nullable=True),
    sa.Column('mobile_voting_opening', sa.Date(), nullable=True),
    sa.Column('mobile_voting_deadline', sa.Date(), nullable=True),
    sa.Column('online_voting_opening', sa.Date(), nullable=True),
    sa.Column('online_voting_deadline', sa.Date(), nullable=True),
    sa.Column('in_person_election_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('position_type', sa.String(), nullable=True),
    sa.Column('position_term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_polls_election_id_elections')),
    sa.ForeignKeyConstraint(['position_term_id'], ['terms.id'], name=op.f('fk_polls_position_term_id_terms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('representatives_id', sa.Integer(), nullable=True),
    sa.Column('term_name', sa.String(), nullable=True),
    sa.Column('term_type', sa.String(), nullable=True),
    sa.Column('term_start_date', sa.Date(), nullable=True),
    sa.Column('term_end_date', sa.Date(), nullable=True),
    sa.Column('term_length', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_terms_poll_id_polls')),
    sa.ForeignKeyConstraint(['representatives_id'], ['representatives.id'], name=op.f('fk_terms_representatives_id_representatives')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voting_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('early_voting', sa.Boolean(), nullable=True),
    sa.Column('vote_by_mail', sa.Boolean(), nullable=True),
    sa.Column('in_person_voting', sa.Boolean(), nullable=True),
    sa.Column('mobile_voting', sa.Boolean(), nullable=True),
    sa.Column('online_voting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('candidate_type', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_candidates_party_id_parties')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rep_type', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_representatives_party_id_parties')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_states_country_id_countries')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('verifification_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_admin_account_id_accounts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('candidate_statement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_campaigns_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_campaigns_poll_id_polls')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_campaigns_representative_id_representatives')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_counties_state_id_states')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_partners_account_id_accounts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_super_admin_account_id_accounts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('voters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('street_line1', sa.String(), nullable=True),
    sa.Column('street_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('veteran_status', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('voter_registration_status', sa.String(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_voters_account_id_accounts')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_voters_party_id_parties')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('administrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('administration_type', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('verifification_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_administrations_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', 'admin_id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('administration_id', sa.Integer(), nullable=True),
    sa.Column('super_admin_id', sa.Integer(), nullable=True),
    sa.Column('deadlines_id', sa.Integer(), nullable=True),
    sa.Column('options_id', sa.Integer(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('election_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['administration_id'], ['admin.id'], name=op.f('fk_elections_administration_id_admin')),
    sa.ForeignKeyConstraint(['deadlines_id'], ['election_deadlines.id'], name=op.f('fk_elections_deadlines_id_election_deadlines')),
    sa.ForeignKeyConstraint(['options_id'], ['voting_options.id'], name=op.f('fk_elections_options_id_voting_options')),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admin.id'], name=op.f('fk_elections_super_admin_id_super_admin')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enterprise_type', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_enterprises_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', 'partner_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('partner_id')
    )
    op.create_table('winners',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_winners_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_winners_poll_id_polls')),
    sa.PrimaryKeyConstraint('poll_id', 'campaign_id')
    )
    op.create_table('ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('polling_location_1', sa.String(), nullable=True),
    sa.Column('polling_location_2', sa.String(), nullable=True),
    sa.Column('polling_location_3', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_ballots_election_id_elections')),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name=op.f('fk_ballots_voter_id_voters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('administration_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['administration_id'], ['administrations.id'], name=op.f('fk_follows_administration_id_administrations')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_follows_bill_id_bills')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_follows_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_follows_county_id_counties')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_follows_election_id_elections')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_follows_enterprise_id_enterprises')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_follows_party_id_parties')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_follows_representative_id_representatives')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_follows_state_id_states')),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name=op.f('fk_follows_voter_id_voters')),
    sa.PrimaryKeyConstraint('id', 'voter_id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('administration_id', sa.Integer(), nullable=True),
    sa.Column('profile_photo', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_members_account_id_accounts')),
    sa.ForeignKeyConstraint(['administration_id'], ['administrations.id'], name=op.f('fk_members_administration_id_administrations')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_members_enterprise_id_enterprises')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('administration_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['administration_id'], ['administrations.id'], name=op.f('fk_posts_administration_id_administrations')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_posts_bill_id_bills')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_posts_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_posts_county_id_counties')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_posts_election_id_elections')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_posts_enterprise_id_enterprises')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_posts_party_id_parties')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_posts_representative_id_representatives')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_posts_state_id_states')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('yes_votes', sa.Integer(), nullable=True),
    sa.Column('no_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_propositions_bill_id_bills')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_propositions_election_id_elections')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_voter_guides_election_id_elections')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_voter_guides_enterprise_id_enterprises')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('super_admin_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.Column('ballot_id', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('representative_id', sa.Integer(), nullable=True),
    sa.Column('administration_id', sa.Integer(), nullable=True),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_notifications_admin_id_admin')),
    sa.ForeignKeyConstraint(['administration_id'], ['administrations.id'], name=op.f('fk_notifications_administration_id_administrations')),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], name=op.f('fk_notifications_ballot_id_ballots')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_notifications_bill_id_bills')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_notifications_candidate_id_candidates')),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('fk_notifications_county_id_counties')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_notifications_election_id_elections')),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], name=op.f('fk_notifications_enterprise_id_enterprises')),
    sa.ForeignKeyConstraint(['guide_id'], ['voter_guides.id'], name=op.f('fk_notifications_guide_id_voter_guides')),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_notifications_member_id_members')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_notifications_partner_id_partners')),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], name=op.f('fk_notifications_party_id_parties')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_notifications_post_id_posts')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_notifications_representative_id_representatives')),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name=op.f('fk_notifications_state_id_states')),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admin.id'], name=op.f('fk_notifications_super_admin_id_super_admin')),
    sa.ForeignKeyConstraint(['voter_id'], ['voters.id'], name=op.f('fk_notifications_voter_id_voters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('proposition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_recommendations_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['guide_id'], ['voter_guides.id'], name=op.f('fk_recommendations_guide_id_voter_guides')),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], name=op.f('fk_recommendations_proposition_id_propositions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('proposition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], name=op.f('fk_votes_ballot_id_ballots')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_votes_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['proposition_id'], ['propositions.id'], name=op.f('fk_votes_proposition_id_propositions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('recommendations')
    op.drop_table('notifications')
    op.drop_table('voter_guides')
    op.drop_table('propositions')
    op.drop_table('posts')
    op.drop_table('members')
    op.drop_table('follows')
    op.drop_table('ballots')
    op.drop_table('winners')
    op.drop_table('enterprises')
    op.drop_table('elections')
    op.drop_table('administrations')
    op.drop_table('voters')
    op.drop_table('super_admin')
    op.drop_table('partners')
    op.drop_table('counties')
    op.drop_table('campaigns')
    op.drop_table('admin')
    op.drop_table('states')
    op.drop_table('representatives')
    op.drop_table('candidates')
    op.drop_table('accounts')
    op.drop_table('voting_options')
    op.drop_table('users')
    op.drop_table('terms')
    op.drop_table('polls')
    op.drop_table('parties')
    op.drop_table('election_deadlines')
    op.drop_table('countries')
    op.drop_table('bills')
    # ### end Alembic commands ###
